/// @Author: Thaivtm thaivtm2003@gmail.com
/// @Date: 2024-07-18 14:36:24
/// @LastEditors: Thaivtm thaivtm2003@gmail.com
/// @LastEditTime: 2024-07-18 14:36:30
/// @FilePath: lib/res/assets_res.dart
/// @Description: 这是默认设置,可以在设置》工具》File Description中进行配置
/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'flutter_application_1';
  static const String PLUGIN_VERSION = '1.0.0+1';
}
