import 'package:flutter/material.dart';

class PrivacyPolicy extends StatelessWidget {
  const PrivacyPolicy({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Privacy Policy'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Privacy Policy',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            const SizedBox(height: 8.0),
            const Text('Last updated: June 04, 2024'),
            const SizedBox(height: 16.0),
            Text(
              'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 16.0),
            Text(
              'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 16.0),
            Text(
              'Interpretation and Definitions',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Interpretation',
              style: Theme.of(context).textTheme.titleLarge,
            ),
            const SizedBox(height: 8.0),
            Text(
              'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 16.0),
            Text(
              'Definitions',
              style: Theme.of(context).textTheme.titleLarge,
            ),
            const SizedBox(height: 8.0),
            Text(
              'For the purposes of this Privacy Policy:',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 8.0),
            const ListTile(
              title: Text('Account'),
              subtitle: Text(
                  'means a unique account created for You to access our Service or parts of our Service.'),
            ),
            const ListTile(
              title: Text('Affiliate'),
              subtitle: Text(
                  'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'),
            ),
            const ListTile(
              title: Text('Application'),
              subtitle: Text(
                  'refers to LMS, the software program provided by the Company.'),
            ),
            const ListTile(
              title: Text('Company'),
              subtitle: Text(
                  'referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to LMS.'),
            ),
            const ListTile(
              title: Text('Country'),
              subtitle: Text('refers to: Vietnam'),
            ),
            const ListTile(
              title: Text('Device'),
              subtitle: Text(
                  'means any device that can access the Service such as a computer, a cellphone or a digital tablet.'),
            ),
            const ListTile(
              title: Text('Personal Data'),
              subtitle: Text(
                  'is any information that relates to an identified or identifiable individual.'),
            ),
            const ListTile(
              title: Text('Service'),
              subtitle: Text('refers to the Application.'),
            ),
            const ListTile(
              title: Text('Service Provider'),
              subtitle: Text(
                  'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.'),
            ),
            const ListTile(
              title: Text('Usage Data'),
              subtitle: Text(
                  'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).'),
            ),
            const ListTile(
              title: Text('You'),
              subtitle: Text(
                  'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.'),
            ),
            const SizedBox(height: 16.0),
            Text(
              'Collecting and Using Your Personal Data',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Types of Data Collected',
              style: Theme.of(context).textTheme.titleLarge,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Personal Data',
              style: Theme.of(context).textTheme.titleLarge,
            ),
            const SizedBox(height: 8.0),
            Text(
              'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const ListTile(
              title: Text('Email address'),
            ),
            const ListTile(
              title: Text('First name and last name'),
            ),
            const ListTile(
              title: Text('Phone number'),
            ),
            const ListTile(
              title: Text('Usage Data'),
            ),
            const SizedBox(height: 16.0),
            Text(
              'Usage Data',
              style: Theme.of(context).textTheme.titleLarge,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Usage Data is collected automatically when using the Service.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IPaddress), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            Text(
              'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 8.0),
            Text(
              'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 16.0),
            Text(
              'Use of Your Personal Data',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 8.0),
            Text(
              'The Company may use Personal Data for the following purposes:',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const ListTile(
              title: Text(
                  'To provide and maintain our Service, including to monitor the usage of our Service.'),
            ),
            const ListTile(
              title: Text(
                  'To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.'),
            ),
            const ListTile(
              title: Text(
                  'For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.'),
            ),
            const ListTile(
              title: Text(
                  'To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application\'s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.'),
            ),
            const ListTile(
              title: Text(
                  'To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.'),
            ),
            const ListTile(
              title: Text(
                  'To manage Your requests: To attend and manage Your requests to Us.'),
            ),
            const ListTile(
              title: Text(
                  'For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.'),
            ),
            const ListTile(
              title: Text(
                  'For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.'),
            ),
            const SizedBox(height: 16.0),
            Text(
              'We may share Your personal information in the following situations:',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const ListTile(
              title: Text(
                  'With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.'),
            ),
            const ListTile(
              title: Text(
                  'For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.'),
            ),
            const ListTile(
              title: Text(
                  'With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.'),
            ),
            const ListTile(
              title: Text(
                  'With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.'),
            ),
            const ListTile(
              title: Text(
                  'With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.'),
            ),
            const ListTile(
                title: Text(
                    'With Your consent: We may disclose Your personal information for any other purpose with Your consent.')),
            const SizedBox(height: 16.0),
            Text(
              'Retention of Your Personal Data',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 8.0),
            Text(
              'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 8.0),
            Text(
              'The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 16.0),
            Text(
              'Transfer of Your Personal Data',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Your information, including Personal Data, is processed at the Company\'s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of Your jurisdiction.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 8.0),
            Text(
              'The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 16.0),
            Text(
              'Disclosure of Your Personal Data',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Business Transactions',
              style: Theme.of(context).textTheme.titleLarge,
            ),
            const SizedBox(height: 8.0),
            Text(
              'If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Law enforcement',
              style: Theme.of(context).textTheme.titleLarge,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Other legal requirements',
              style: Theme.of(context).textTheme.titleLarge,
            ),
            const SizedBox(height: 8.0),
            Text(
              'The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const ListTile(
              title: Text('Comply with a legal obligation'),
            ),
            const ListTile(
              title: Text(
                  'Protect and defend the rights or property of the Company'),
            ),
            const ListTile(
              title: Text(
                  'Prevent or investigate possible wrongdoing in connection with the Service'),
            ),
            const ListTile(
              title: Text(
                  'Protect the personal safety of Users of the Service or the public'),
            ),
            const ListTile(
              title: Text('Protect against legal liability'),
            ),
            const SizedBox(height: 16.0),
            Text(
              'Security of Your Personal Data',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 8.0),
            const Text(
              'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.',
            ),
            const SizedBox(height: 16.0),
            Text(
              'Children\'s Privacy',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 8.0),
            Text(
              'Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 16.0),
            Text(
              'Changes to This Privacy Policy',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 8.0),
            Text(
              'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 8.0),
            Text(
              'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 8.0),
            Text(
              'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 16.0),
            Text(
              'Contact Us',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 8.0),
            Text(
              'If you have any questions about this Privacy Policy, You can contact us:',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const ListTile(
              title: Text('By email: thaivtm2003@gmail.com'),
            ),
            const ListTile(
              title: Text('By phone number: 0918181480'),
            ),
          ],
        ),
      ),
    );
  }
}
